# Yarn configuration file
nodeLinker: node-modules

# Enable PnP (Plug'n'Play) for better performance
# Uncomment the line below if you want to use PnP
# nodeLinker: pnp

# Ignore engine requirements for development
enableGlobalCache: true

# Set the default registry
npmRegistryServer: 'https://registry.npmjs.org'

# Ignore engine checks for development
enableScripts: true
