name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Check formatting
        run: yarn format:check

      - name: Type check
        run: yarn tsc

      - name: Build
        run: yarn build

      - name: Test with coverage
        run: yarn test:coverage

      - name: Test installation process
        run: ./test-install.sh
